### ISSUE TITLE
Support Java 11

### ISSUE THREAD

**Issue by kkorotkov** [Labs64/swid-generator#1] opened 2019-02-01 09:48 UTC

**Comment by Loniks** [comment] 2019-10-05 09:08
Hi, @kkorotkov @r-brown  I would like to work with this task in the scope of Hacktoberfest. Could you please assign it to me?

**Comment by r-brown** [comment] 2019-10-05 14:23
Hello @Loniks - sure & thank you for the contribution!

**Comment by Loniks** [comment] 2019-10-06 13:50
Hi, @r-brown @kkorotkov I have a few questions to you:
1. As I see from docs this library requires J2SE 1.6 or never. Does that mean that the goal of this migration is to use JVM 11 during the build and provide to clients sources that support JVM 6? Or we want to update the minimum version of J2SE?
2. During the migration of maven build to JVM 11 I have found an issue with generation java docs for autogenerated package **org.w3._2000._09.xmldsig_** This is a known JVM issue caused by **@link byte[]** line in any comment in Java file. In our case, this comment happens in the autogenerated code inside the mentioned package. To generate JavaDoc I have to exclude this package from docs. Does this solution work for you?

**Comment by r-brown** [comment] 2019-10-06 15:38
Hi @Loniks
After verifying [Oracle Java SE Support Roadmap](https://www.oracle.com/technetwork/java/java-se-support-roadmap.html) I'd say there is no need to maintain old (not supported versions).
So, we can set Java 8 as a min. supported version.

**Comment by r-brown** [comment] 2019-10-06 15:42
Exclusion of `org.w3._2000.09.xmldsig` from the JavaDoc is OK, as this is not the main part of the library.

**Comment by Loniks** [comment] 2019-10-07 17:47
Got it. So I have prepared P/R updated source version to 1.8 and excluded mention package from JavaDoc Please review #2

**Closed as completed** 2019-10-08 05:23 UTC
Labels: Hacktoberfest

**Comment by r-brown** [comment] 2019-10-08 05:24
Post merge tasks:
- keept Java8 envs in Travis as min. supported version
- changed `dist: trusty` to resolve the issue with `oraclejdk8`
